"""add trigger to document node

Revision ID: 11d52f68e684
Revises: 9215c8c48b89
Create Date: 2026-07-12 17:09:29.305824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11d52f68e684'
down_revision = '9215c8c48b89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_nodes', sa.Column('trigger', sa.String(), nullable=True))
    
    # Update existing project nodes with the trigger value from projects table
    op.execute(
        "UPDATE document_nodes dn "
        "SET trigger = p.trigger "
        "FROM projects p "
        "WHERE dn.id = p.id"
    )
    
    # For child nodes/any other nodes, default to 'on_advance'
    op.execute(
        "UPDATE document_nodes "
        "SET trigger = 'on_advance' "
        "WHERE trigger IS NULL"
    )
    
    # Make column nullable=False
    op.alter_column('document_nodes', 'trigger', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_nodes', schema=None) as batch_op:
        batch_op.drop_column('trigger')

    # ### end Alembic commands ###
