"""Initial migration

Revision ID: 18404848a92b
Revises: 
Create Date: 2026-07-05 16:47:55.785226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18404848a92b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('genre', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('audience', sa.String(), nullable=True),
    sa.Column('tone', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('target_length', sa.String(), nullable=True),
    sa.Column('constraints', sa.JSON(), nullable=True),
    sa.Column('current_stage', sa.String(), nullable=False),
    sa.Column('agent_set', sa.String(), nullable=True),
    sa.Column('trigger', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_nodes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('node_type', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['document_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('document_node_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('call_type', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('user_prompt', sa.Text(), nullable=True),
    sa.Column('system_chars', sa.Integer(), nullable=False),
    sa.Column('user_chars', sa.Integer(), nullable=False),
    sa.Column('trace_id', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('queries', sa.Integer(), nullable=True),
    sa.Column('results', sa.Integer(), nullable=True),
    sa.Column('cached', sa.Boolean(), nullable=True),
    sa.Column('used_fallback', sa.Boolean(), nullable=True),
    sa.Column('decision', sa.String(), nullable=True),
    sa.Column('critique', sa.Text(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_node_id'], ['document_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_node_id', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('flesch_ease', sa.Float(), nullable=False),
    sa.Column('flesch_kincaid', sa.Float(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('sentence_count', sa.Integer(), nullable=False),
    sa.Column('avg_sentence_length', sa.Float(), nullable=False),
    sa.Column('type_token_ratio', sa.Float(), nullable=False),
    sa.Column('passive_voice_pct', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_node_id'], ['document_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stage_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_node_id', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('loop_count', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('decision', sa.String(), nullable=True),
    sa.Column('critique', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_node_id'], ['document_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stage_states')
    op.drop_table('metrics')
    op.drop_table('agent_logs')
    op.drop_table('document_nodes')
    op.drop_table('projects')
    # ### end Alembic commands ###
