"""add_persistent_stage_fields

Revision ID: 859088cbc140
Revises: 18404848a92b
Create Date: 2026-07-12 16:09:07.344688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '859088cbc140'
down_revision = '18404848a92b'
branch_labels = None
depends_on = None


def upgrade():
    # 1. Add columns as nullable first
    with op.batch_alter_table('stage_states', schema=None) as batch_op:
        batch_op.add_column(sa.Column('iteration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('prompt_template_path', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('system_prompt', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('user_prompt', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('output_text', sa.Text(), nullable=True))

    # 2. Data migration: copy and map old values to new columns
    bind = op.get_bind()
    bind.execute(sa.text("UPDATE stage_states SET iteration = COALESCE(loop_count, 0) + 1"))
    bind.execute(sa.text("UPDATE stage_states SET is_active = True"))
    bind.execute(sa.text("UPDATE stage_states SET status = CASE WHEN state = 'ready' THEN 'completed' WHEN state IN ('empty', 'fresh') THEN 'new' WHEN state = 'generating' THEN 'processing' ELSE COALESCE(state, 'new') END"))
    bind.execute(sa.text("UPDATE stage_states SET output_text = COALESCE(body, critique, decision)"))

    # 3. Alter columns to be NOT NULL
    with op.batch_alter_table('stage_states', schema=None) as batch_op:
        batch_op.alter_column('iteration', nullable=False)
        batch_op.alter_column('is_active', nullable=False)
        batch_op.alter_column('status', nullable=False)

    # 4. Drop old columns
    with op.batch_alter_table('stage_states', schema=None) as batch_op:
        batch_op.drop_column('decision')
        batch_op.drop_column('body')
        batch_op.drop_column('state')
        batch_op.drop_column('loop_count')
        batch_op.drop_column('critique')


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stage_states', schema=None) as batch_op:
        batch_op.add_column(sa.Column('critique', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('loop_count', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('body', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('decision', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('output_text')
        batch_op.drop_column('user_prompt')
        batch_op.drop_column('system_prompt')
        batch_op.drop_column('prompt_template_path')
        batch_op.drop_column('status')
        batch_op.drop_column('is_active')
        batch_op.drop_column('iteration')

    # ### end Alembic commands ###
