"""add_project_revision_strategy

Revision ID: 9215c8c48b89
Revises: 859088cbc140
Create Date: 2026-07-12 16:20:16.649704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9215c8c48b89'
down_revision = '859088cbc140'
branch_labels = None
depends_on = None


def upgrade():
    # 1. Add column as nullable first
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('revision_strategy', sa.String(), nullable=True))

    # 2. Populate existing records with default value
    bind = op.get_bind()
    bind.execute(sa.text("UPDATE projects SET revision_strategy = 'cascade'"))

    # 3. Alter column to NOT NULL
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('revision_strategy', nullable=False)



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('revision_strategy')

    # ### end Alembic commands ###
